// <auto-generated />
namespace SVSU_Capstone_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class uniqueIndexed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uniqueIndexed));
        
        string IMigrationMetadata.Id
        {
            get { return "202203022316526_uniqueIndexed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
