// <auto-generated />
namespace SVSU_Capstone_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class checkedItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(checkedItem));
        
        string IMigrationMetadata.Id
        {
            get { return "202202110222519_checkedItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
